#!/usr/bin/env python3
"""
Write PR Stats to SQLite Database

Reads PR statistics CSV files generated by prStatsAggregator.py and imports
them into the SQLite database pr_stats table. By default, CSV files are deleted
after successful import.

Usage:
    python prStatsWriteToDB.py [--db-path PATH] [--stats-folder PATH] [--keep-files]
    
    --keep-files: Keep CSV files after import (default: delete after successful import)
"""

import sqlite3
import csv
import argparse
import os
from pathlib import Path
from typing import List, Dict, Optional
from common import load_all_config


def connect_to_database(db_path: Path, quiet: bool = False) -> Optional[sqlite3.Connection]:
    """
    Connect to the SQLite database.
    
    Args:
        db_path: Path to the database file
        quiet: If True, suppress print statements (default: False)
    
    Returns:
        Database connection or None if failed
    """
    if not db_path.exists():
        if not quiet:
            print(f"❌ Database not found at: {db_path}")
        return None
    
    if not quiet:
        print(f"📁 Connecting to database: {db_path}")
    
    try:
        conn = sqlite3.connect(str(db_path))
        return conn
    except Exception as e:
        if not quiet:
            print(f"❌ Error connecting to database: {e}")
        return None


def parse_bool(value: str) -> int:
    """
    Convert boolean string or value to integer (0 or 1).
    
    Args:
        value: String representation of boolean
    
    Returns:
        1 for True/true/1, 0 for False/false/0 or empty
    """
    if not value or value == '':
        return 0
    
    value_str = str(value).lower().strip()
    
    if value_str in ['true', '1', 'yes']:
        return 1
    elif value_str in ['false', '0', 'no']:
        return 0
    else:
        return 0


def parse_goal_id(value: str) -> Optional[int]:
    """
    Parse goal_id (okr column from CSV).
    
    Args:
        value: String representation of goal ID
    
    Returns:
        Integer goal ID or None if empty/invalid
    """
    if not value or value == '':
        return None
    
    try:
        return int(value)
    except (ValueError, TypeError):
        return None


def parse_confidence(value: str) -> Optional[float]:
    """
    Parse confidence score.
    
    Args:
        value: String representation of confidence
    
    Returns:
        Float confidence or None if empty/invalid
    """
    if not value or value == '':
        return None
    
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


def import_pr_stats_from_csv(conn: sqlite3.Connection, csv_path: Path, quiet: bool = False) -> Dict:
    """
    Import PR stats from a single CSV file into the database.
    
    Args:
        conn: Database connection
        csv_path: Path to CSV file
        quiet: If True, suppress print statements
    
    Returns:
        Dictionary with import results (inserted, updated, errors)
    """
    if not csv_path.exists():
        if not quiet:
            print(f"   ⚠️  CSV file not found: {csv_path}")
        return {'inserted': 0, 'updated': 0, 'errors': 0}
    
    inserted = 0
    updated = 0
    errors = 0
    
    try:
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            
            for row in reader:
                try:
                    # Map CSV columns to database columns
                    username = row.get('username', '').strip()
                    pr_id = int(row.get('pr_id', 0))
                    reviewed_authored = row.get('reviewed_authored', '').strip()
                    goal_id = parse_goal_id(row.get('okr', ''))
                    category = row.get('category', '').strip() or None
                    created_time = row.get('created_time', '').strip() or None
                    confidence = parse_confidence(row.get('confidence', ''))
                    author_of_pr = row.get('author_of_pr', '').strip() or None
                    repo = row.get('repo', '').strip() or None
                    is_ai_author = parse_bool(row.get('is-ai-author', ''))
                    
                    # Validate required fields
                    if not username or not pr_id or not reviewed_authored:
                        errors += 1
                        if not quiet:
                            print(f"   ⚠️  Skipping row with missing required fields: {row}")
                        continue
                    
                    # Check if record exists
                    check_stmt = conn.execute(
                        """
                        SELECT COUNT(*) FROM pr_stats 
                        WHERE username = ? AND pr_id = ? AND reviewed_authored = ?
                        """,
                        (username, pr_id, reviewed_authored)
                    )
                    exists = check_stmt.fetchone()[0] > 0
                    
                    # Insert or replace record
                    insert_stmt = conn.execute(
                        """
                        INSERT OR REPLACE INTO pr_stats 
                        (username, pr_id, reviewed_authored, goal_id, category, created_time, 
                         confidence, author_of_pr, repo, is_ai_author)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (username, pr_id, reviewed_authored, goal_id, category, created_time,
                         confidence, author_of_pr, repo, is_ai_author)
                    )
                    
                    if exists:
                        updated += 1
                    else:
                        inserted += 1
                
                except Exception as e:
                    errors += 1
                    if not quiet:
                        print(f"   ❌ Error processing row: {e}")
                        print(f"      Row data: {row}")
        
        # Commit all changes
        conn.commit()
        
        if not quiet:
            print(f"   ✅ Processed: {csv_path.name}")
            print(f"      Inserted: {inserted}")
            print(f"      Updated: {updated}")
            print(f"      Errors: {errors}")
    
    except Exception as e:
        if not quiet:
            print(f"   ❌ Error reading CSV file: {e}")
        return {'inserted': 0, 'updated': 0, 'errors': errors + 1}
    
    return {'inserted': inserted, 'updated': updated, 'errors': errors}


def import_all_pr_stats(db_path: Path, stats_folder: Path, quiet: bool = False, delete_after_import: bool = True) -> Dict:
    """
    Import all PR stats CSV files from the stats folder.
    
    Args:
        db_path: Path to the database file
        stats_folder: Path to folder containing PR stats CSV files
        quiet: If True, suppress print statements
        delete_after_import: If True, delete CSV files after successful import (default: True)
    
    Returns:
        Dictionary with total import results
    """
    if not stats_folder.exists():
        if not quiet:
            print(f"❌ Stats folder not found: {stats_folder}")
        return {'total_files': 0, 'inserted': 0, 'updated': 0, 'errors': 0}
    
    conn = connect_to_database(db_path, quiet)
    if not conn:
        return {'total_files': 0, 'inserted': 0, 'updated': 0, 'errors': 1}
    
    try:
        # Find all pr_*.csv files in stats folder
        csv_files = list(stats_folder.glob('pr_*.csv'))
        
        if not csv_files:
            if not quiet:
                print(f"⚠️  No CSV files found in: {stats_folder}")
            return {'total_files': 0, 'inserted': 0, 'updated': 0, 'errors': 0}
        
        if not quiet:
            print(f"\n{'='*80}")
            print(f"📊 Found {len(csv_files)} CSV file(s) to import")
            print(f"{'='*80}\n")
        
        total_inserted = 0
        total_updated = 0
        total_errors = 0
        total_deleted = 0
        
        for csv_file in csv_files:
            if not quiet:
                print(f"📄 Importing: {csv_file.name}")
            
            result = import_pr_stats_from_csv(conn, csv_file, quiet)
            total_inserted += result['inserted']
            total_updated += result['updated']
            total_errors += result['errors']
            
            # Delete file after successful import (if no errors)
            if delete_after_import and result['errors'] == 0:
                try:
                    os.remove(csv_file)
                    total_deleted += 1
                    if not quiet:
                        print(f"   🗑️  Deleted: {csv_file.name}")
                except Exception as e:
                    if not quiet:
                        print(f"   ⚠️  Failed to delete {csv_file.name}: {e}")
        
        if not quiet:
            print(f"\n{'='*80}")
            print(f"✅ Import Summary")
            print(f"{'='*80}")
            print(f"Total files: {len(csv_files)}")
            print(f"Total inserted: {total_inserted}")
            print(f"Total updated: {total_updated}")
            print(f"Total errors: {total_errors}")
            if delete_after_import:
                print(f"Total deleted: {total_deleted}")
            print(f"{'='*80}\n")
        
        return {
            'total_files': len(csv_files),
            'inserted': total_inserted,
            'updated': total_updated,
            'errors': total_errors,
            'deleted': total_deleted
        }
    
    finally:
        conn.close()
        if not quiet:
            print("✅ Database connection closed")


def main():
    """Main function"""
    parser = argparse.ArgumentParser(
        description='Import PR statistics from CSV files into SQLite database'
    )
    parser.add_argument(
        '--db-path',
        type=str,
        help='Path to the SQLite database file (default: from pipeline_config.json)'
    )
    parser.add_argument(
        '--stats-folder',
        type=str,
        help='Path to the folder containing PR stats CSV files (default: from pipeline_config.json)'
    )
    parser.add_argument(
        '--keep-files',
        action='store_true',
        help='Keep CSV files after import (default: delete after successful import)'
    )
    
    args = parser.parse_args()
    
    print("=" * 80)
    print("Write PR Stats to Database")
    print("=" * 80)
    print()
    
    # Load configuration
    all_config = load_all_config()
    paths = all_config['paths']
    base_dir = paths['base_dir']
    pr_data_folder = paths['pr_data_folder']
    
    # Determine database path
    if args.db_path:
        db_path = Path(args.db_path)
    else:
        db_path = base_dir / "database.dev.db"
    
    # Determine stats folder path
    if args.stats_folder:
        stats_folder = Path(args.stats_folder)
    else:
        stats_folder = pr_data_folder / "pr-stats"
    
    print(f"📁 Database: {db_path}")
    print(f"📂 Stats folder: {stats_folder}")
    print(f"🗑️  Delete after import: {not args.keep_files}")
    print()
    
    # Import all PR stats
    delete_after_import = not args.keep_files
    result = import_all_pr_stats(db_path, stats_folder, delete_after_import=delete_after_import)
    
    # Exit with appropriate code
    if result['errors'] > 0:
        exit(1)
    else:
        exit(0)


if __name__ == "__main__":
    main()
