package com.example.fiq.generic;

public enum GenericBeanType {
    OKR, OKR_STATUS, USER_PROFILE, WEBSITE_CRAWL_DETAIL, COMPANY_PROFILE, BENCHMARK_REPORT_TASK, COMPANY_BENCHMARK_REPORT, COMPETITOR_SUGGESTION, BENCHMARK_REQUEST_EVENT, INDUSTRY_BENCHMARK_CONFIG, INDUSTRY_BENCHMARK
}
